title: Michele Iarossi
logo: /assets/img/IMG_2391.jpg
email: michele@mathsophy.com
blank_title: true
favicon: true
description: ""
show_downloads: false
color-scheme: light
plugins:
  - jekyll-remote-theme
remote_theme: BDHU/minimalist
